[WIP] Add terminate with TerminateFlag
HiroIshida/mohou_ros pull request #61
Opened 2022-09-03 18:10 UTC by Kanazawanaoaki

Added the ability to terminate skill execution when `TerminateFlag` reaches or exceeds a threshold value and the skill side is determined to be terminated.  
Add `terminate_threthold` argument and slot, and implement using `is_terminatable`, which was originally implemented in ExecutorBase.  

I haven't checked it on the real robot yet, so I will check it tomorrow after the test passes.

2022-09-04 01:22 UTC, HiroIshida requested changes

2022-09-04 01:22 UTC, HiroIshida commented on scripts/pr2/execute_pr2.py
> +    tf_thre: float = args.tf
tf_thre => threshold_threshold 
If name is too long it's always better to name it expressively

2022-09-04 01:22 UTC, HiroIshida commented on mohou_ros_utils/executor.py
> +        self, project_path: Path, dryrun=True, save_rosbag=True, terminate_threthold=0.98
add type annotation `float` to `terminate_threshold`

2022-09-04 01:22 UTC, HiroIshida commented on scripts/pr2/execute_pr2.py
> +    parser.add_argument("-tf", type=float, default=0.8, help="threthold of terminate flag")
`tf` is bit confusing because of `tf` library exists on ros.

2022-09-04 01:23 UTC, HiroIshida commented
@Kanazawanaoaki 
Thanks for you PR! please fix the PR according to the review I posted.

2022-09-04 01:25 UTC, HiroIshida requested changes

2022-09-04 01:25 UTC, HiroIshida commented on scripts/pr2/execute_pr2.py
> +    parser.add_argument("--terminate", action="store_true", help="use terminate flag")
verb "use" in "use terminate flag" is bit ambiguous. something like `terminate using terminate flag` is better

2022-09-04 08:13 UTC, Kanazawanaoaki commented
Thanks for the review! I have fixed the part you commented on and tested it on the real robot to make sure it works.  
If everything looks good, I''ll combine the commits into one or two.

2022-09-04 15:31 UTC, HiroIshida commented
LGTM! 
I will merge this immedeately after you squash the commit logs

2022-09-05 10:52 UTC, Kanazawanaoaki commented
I understand.  
I squashed the commit log and rebased this branch on master.

2022-09-05 12:11 UTC, merged